apiVersion: scope.github.com/v1alpha
kind: ScopeDoctorCheck
metadata:
  name: path-exists
  description: Check your shell for basic functionality
spec:
  check:
    target: ./scripts/fail-first-call path-exists
  fix:
    target: ../bin/truey
  help: You're shell does not have a path env. Reload your shell.
