#---
#apiVersion: scope.github.com/v1alpha
#kind: ScopeReportLocation
#metadata:
#  name: report
#spec:
#  destination:
#    rustyPaste:
#      url: http://localhost:8000
#---
#apiVersion: scope.github.com/v1alpha
#kind: ScopeReportLocation
#metadata:
#  name: github
#spec:
#  destination:
#    githubIssue:
#      owner: ethankhall
#      repo: dummy-repo
---
apiVersion: scope.github.com/v1alpha
kind: ScopeReportLocation
metadata:
  name: local
spec:
  additionalData:
    username: id -nu
    ruby: which ruby
    node: which node
    nodeVersion: node -v
  templates:
    analyze: |
      # There was an error!
  
      When running `{{ command }}` scope ran into an error
  destination:
    local:
      directory: /tmp/scope/foo/
---
apiVersion: scope.github.com/v1alpha
kind: ScopeReportLocation
metadata:
  name: sample
spec:
  additionalData:
    username: id -nu
    ruby: which ruby
    node: which node
    nodeVersion: node -v
  destination:
    local:
      directory: /tmp/scope/foo/