#!/bin/bash
set -eux

NAME=$1
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
mkdir "${SCRIPT_DIR}/tmp" || true

if [ -f "${SCRIPT_DIR}/tmp/${NAME}" ]; then
  exit 0
else
  touch "${SCRIPT_DIR}/tmp/${NAME}"
  exit 1
fi