---
apiVersion: scope.github.com/v1alpha
kind: ScopeReportLocation
metadata:
  name: report
spec:
  destination:
    rustyPaste:
      url: http://localhost:8000
---
apiVersion: scope.github.com/v1alpha
kind: ScopeReportLocation
metadata:
  name: github
spec:
  destination:
    githubIssue:
      owner: ethankhall
      repo: dummy-repo
---
apiVersion: scope.github.com/v1alpha
kind: ScopeReportDefinition
metadata:
  name: github
spec:
  additionalData:
    username: id -u
    ruby: which ruby
    node: which node
    nodeVersion: node -v
  template: |
    # There was an error!
    
    When running `{{ command }}` scope ran into an error