on: [pull_request]

name: Continuous integration

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      artifacts: ${{ steps.filter.outputs.artifacts }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            artifacts:
              - '**/*.rs'
              - 'Cargo.*'
              - '**/Cargo.*'
              - 'Cross.toml'
              - '.github/bin/*'
              - '.github/workflows/*'
              - 'rust-toolchain.toml'
            docs:
              - 'docs/**'
              - '.github/workflows/*'
  tests:
    needs: [ filter ]
    if: ${{ needs.filter.outputs.artifacts == 'true' }}
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - name: cargo build
        run: cargo build
      - name: cargo check
        run: cargo check
      ## Cargo test
      - name: cargo test
        run: cargo test
      - name: check for changes
        run: git diff --quiet && git diff --cached --quiet
      ## Cargo fmt
      - run: rustup component add rustfmt
      - name: cargo fmt
        run:  cargo fmt --all -- --check
      ## Cargo clippy
      - name: cargo clippy
        run: cargo clippy -- -D warnings

  build-docs:
    needs: [ filter ]
    if: ${{ needs.filter.outputs.docs == 'true' }}
    uses: ./.github/workflows/gh-page.yml

  check:
    if: always()
    needs:
      - build-docs
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: build-docs,build-artifacts,tests
          jobs: ${{ toJSON(needs) }}
